[tool.ruff]
ignore = [
    "E501",
    "F821",
]
select = [
    "E",
    "F",
    "W",
    "I",
]

line-length = 119

[tool.ruff.isort]
force-single-line = true

[tool.ruff.per-file-ignores]
"./tests/*" = ["E101"]
